{{- if .Values.prometheus.longtermRetentionDays }}
---
{{- if semverCompare ">= 1.21" .Values.global.discovery.kubernetesVersion }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: prometheus-longterm
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list . (dict "app" "prometheus" "prometheus" "longterm")) | nindent 2 }}
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
      prometheus: longterm
{{- end }}
