apiVersion: v1
kind: Service
metadata:
  name: cuberite
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "cuberite")) | nindent 2 }}
spec:
  selector:
    app: cuberite
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    - protocol: TCP
      port: 25565
      targetPort: 25565
