properties:
  upstreamNameservers:
    description: |
      Список IP-адресов рекурсивных DNS-серверов, которые CoreDNS будет использовать для разрешения внешних доменов.

      По умолчанию - список из `/etc/resolv.conf`.
  hosts:
    description: |
      Статический список хостов в стиле /etc/hosts.
  stubZones:
    description: |
      Список дополнительных зон для обслуживания CoreDNS.
    items:
      properties:
        zone:
          description: |
            Зона CoreDNS.
        upstreamNameservers:
          description: |
            Список IP-адресов рекурсивных DNS-серверов, которые CoreDNS будет использовать для разрешения доменов в этой зоне.
  enableLogs:
    description: |
      Позволяет включить логирование в CoreDNS.
  clusterDomainAliases:
    description: |
      Список альтернативных доменов кластера, разрешаются наравне с `global.discovery.clusterDomain`.
