stages:
  - publish

.base_deploy: &base_deploy
  stage: publish
  script:
  - type trdl && . $(trdl use werf 1.2 ${WERF_CHANNEL})
  - type werf && source $(werf ci-env gitlab --as-file)
  - werf converge
  tags:
  - tfprod-distributed-werf

Stage:
  <<: *base_deploy
  variables:
    WERF_KUBECONFIG_BASE64: "${KUBECONFIG_BASE64_DEV}"
    WERF_NAMESPACE: "deckhouse-web-stage"
    WERF_DIR: "ci"
  environment:
    name: web-stage

Production:
  <<: *base_deploy
  variables:
    WERF_KUBECONFIG_BASE64: "${KUBECONFIG_BASE64_PROD}"
    WERF_NAMESPACE: "deckhouse-web-production"
    WERF_DIR: "ci"
  environment:
    name: web-production
