{{- range $instance := .Values.prometheusPushgateway.instances }}
---
{{- if semverCompare ">= 1.21" .clusterConfiguration.kubernetesVersion }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ $instance }}
  namespace: kube-{{ $.Chart.Name }}
  {{- include "helm_lib_module_labels" (list $ (dict "app" $instance)) | nindent 2 }}
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: {{ $instance }}
{{- end }}
