---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: annotations-converter
{{ include "helm_lib_module_labels" (list . (dict "app" "annotations-converter")) | indent 2 }}
webhooks:
- name: webhook.cert-manager.io
  admissionReviewVersions: ["v1beta1"]
  failurePolicy: Fail
  {{- if semverCompare ">=1.15" .Values.global.discovery.kubernetesVersion }}
  matchPolicy: Equivalent
  {{- end }}
  sideEffects: None
  timeoutSeconds: 3
  clientConfig:
    service:
      name: annotations-converter-webhook
      namespace: d8-cert-manager
      path: "/mutate"
      {{- if semverCompare ">=1.15" .Values.global.discovery.kubernetesVersion }}
      port: 443
    {{- end }}
    caBundle: {{ .Values.certManager.internal.webhookCACrt | b64enc }}
  rules:
  - operations: [ "CREATE", "UPDATE" ]
    apiGroups: ["*"]
    apiVersions: ["*"]
    resources: ["ingresses"]
