{{- if (hasKey .Values.prometheus.internal.alertmanagers "internal") }}
  {{- range .Values.prometheus.internal.alertmanagers.internal }}
---
{{- if semverCompare ">= 1.21" $.Values.global.discovery.kubernetesVersion }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: alertmanager-{{ .name }}
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list $ (dict "app" (printf "alertmanager-%s" .name))) | nindent 2 }}
spec:
  minAvailable: {{ include "helm_lib_is_ha_to_value" (list $ 1 0) }}
  selector:
    matchLabels:
      app.kubernetes.io/name: alertmanager
      alertmanager: {{ .name }}
  {{- end }}
{{- end }}
