kind: ClusterConfiguration
apiVersions:
- apiVersion: deckhouse.io/v1
  openAPISpec:
    type: object
    description: General parameters of a cluster.
    additionalProperties: false
    required: [apiVersion, kind, clusterType, kubernetesVersion, podSubnetCIDR, serviceSubnetCIDR, clusterDomain]
    x-examples:
    - apiVersion: deckhouse.io/v1
      kind: ClusterConfiguration
      podSubnetNodeCIDRPrefix: "24"
      podSubnetCIDR: 10.244.0.0/16
      serviceSubnetCIDR: 192.168.0.0/16
      kubernetesVersion: "1.21"
      clusterDomain: test
      clusterType: "Cloud"
      cloud:
        prefix: test
        provider: Yandex
      packagesProxy:
        uri: https://example.com
        username: user
        password: passwd
    properties:
      apiVersion:
        type: string
        enum: [deckhouse.io/v1, deckhouse.io/v1alpha1]
      kind:
        type: string
        enum: [ClusterConfiguration]
      clusterType:
        type: string
        enum: [Cloud, Static]
      cloud:
        type: object
        description: |
          Type of a cloud provider (if `Cloud` clusterType is used).
        required: [provider]
        additionalProperties: false
        properties:
          provider:
            type: string
            enum:
            - "OpenStack"
            - "AWS"
            - "GCP"
            - "Yandex"
            - "vSphere"
            - "Azure"
          prefix:
            type: string
            description: |
              Prefix to differentiate cluster objects (can be used, e.g., in routing).
            pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
      podSubnetCIDR:
        type: string
        description: Address space of the cluster's Pods.
      podSubnetNodeCIDRPrefix:
        type: string
        description: The prefix of Pod network on a node.
        default: "24"
      serviceSubnetCIDR:
        type: string
        description: |
          Address space of the cluster's services.
      clusterDomain:
        type: string
        description: Cluster domain (used for local routing).
        default: "cluster.local"
      defaultCRI:
        type: string
        description: CRI used in the cluster.
        enum:
        - "Docker"
        - "Containerd"
        - "NotManaged"
        default: "Containerd"
      kubernetesVersion:
        type: string
        description: Kubernetes control plane version to use in a cluster.
        enum:
        - "1.19"
        - "1.20"
        - "1.21"
        - "1.22"
        - "1.23"
        - "1.24"
        - "Automatic"
      packagesProxy:
        type: object
        description: |
          A proxy server for downloading packages (e.g deb or rpm).
        additionalProperties: false
        properties:
          uri:
            type: string
            description: The address of the proxy server.
          username:
            type: string
            description: The username for authenticating with the proxy server.
          password:
            type: string
            description: The password for authenticating with the proxy server.
        oneOf:
          - properties:
              uri:
                type: string
            additionalProperties: false
            required: [uri]
          - properties:
              uri:
                type: string
              username:
                type: string
              password:
                type: string
            additionalProperties: false
            required: [uri, username, password]
    oneOf:
    - properties:
        clusterType:
           enum: [Static]
    - properties:
        clusterType:
           enum: [Cloud]
      cloud: {}
      required: [cloud]
