type: object
properties:
  nodeExporter:
    description: Конфигурация node_exporter
    properties:
      collectors:
        description: Конфигурация коллекторов
        properties:
          systemd:
            description: Конфигурация systemd коллектора
            properties:
              includeUnits:
                description: Регулярное выражения, описывающие systemd unit'ы, которые нужно включить в мониторинг. Указание включит systemd коллектор.
  highAvailability:
    description: |
      Ручное управление режимом отказоустойчивости.

      По умолчанию режим отказоустойчивости определяется автоматически. [Подробнее](../../deckhouse-configure-global.html#параметры) про режим отказоустойчивости.
  nodeSelector:
    description: |
      Структура, аналогичная `spec.nodeSelector` Kubernetes pod.

      Если ничего не указано или указано `false` — будет [использоваться автоматика](https://deckhouse.io/ru/documentation/v1/#выделение-узлов-под-определенный-вид-нагрузки).
  tolerations:
    type: array
    description: |
      Структура, аналогичная  `spec.tolerations` в Kubernetes Pod.

      Если ничего не указано или указано `false` — будет [использоваться автоматика](https://deckhouse.io/ru/documentation/v1/#выделение-узлов-под-определенный-вид-нагрузки).
  vpa:
    type: object
    description: |
      Настройки VPA для деплоймента kube-state-metrics.
    properties:
      kubeStateMetricsMaxCPU:
        description: |
          Настройки лимита CPU в VPA для kube-state-metrics.
      kubeStateMetricsMaxMemory:
        description: |
          Настройки лимита памяти в VPA для kube-state-metrics.
